contacts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'contacts.views.sc_contact_home', name='sc-contact'),
    url(r'^remove-qout/$', 'contacts.views.remove_qout', name='remove_qout'),
    url(r'^test/$', 'contacts.views.contact_test', name='contact-test'),
    url(r'^auto/$', 'contacts.views.autocomplete', name='sc-sugessions'),
    url(r'^search/$', 'contacts.views.search_contact', name='search-contact'),
    url(r'^list/$', 'contacts.views.contact_list', name='sc-contact-list'),
    url(r'^(?P<cid>\d+)/$', 'contacts.views.sc_contact_view', name='sc-contact-view'),

    url(r'^add/rel/$', 'contacts.views.sc_contact_add_rel', name='sc-contact-add'),
    url(r'^add/rel_item/$', 'contacts.views.sc_contact_add_rel_item', name='sc-contact-add-item'),
    url(r'^add/$', 'contacts.views.sc_contact_add', name='sc-contact-add'),
    url(r'^edit/(?P<pk>\d+)/$', 'contacts.views.contact_edit', name='sc-contact-edit'),
    url(r'^edit/basic/(?P<pk>\d+)/$', 'contacts.views.contact_edit_basic', name='sc-contact-edit-basic'),
    url(r'^get-contact/(?P<pk>\d+)/$', 'contacts.views.get_contact', name='get-contact'),

    url(r'^get-contact/hover/(?P<pk>\d+)/$', 'contacts.views.get_contact_hover', name='get-contact-hover'),

    url(r'^update/$', 'contacts.views.contact_update', name='sc-contact-update'),
    url(r'^profile/update/$', 'contacts.views.profile_update', name='sc-profile-update'),
    
    url(r'^delete/$', 'contacts.views.contact_delete', name='sc-contact-delete'),


    url(r'^profile/$', 'contacts.views.sc_profile', name='sc-profile'),
    
    # url(r'^update/$', 'contacts.views.sc_update', name='sc-update'),
    
    url(r'^phone/$', 'contacts.views.sc_phone_list', name='sc-phone-list'),
    url(r'^phone/add/$', 'contacts.views.contact_phone_add', name='sc-phone-add-ajax'),
    url(r'^phone/edit/(?P<pid>\d+)/$', 'contacts.views.contact_phone_edit', name='sc-phone-edit'),
    url(r'^phone/delete/$', 'contacts.views.sc_phone_delete', name='sc-phone-delete'),

    url(r'^terms/$', 'contacts.views.view_terms', name='sc-term'),
    url(r'^terms/json/$', 'contacts.views.view_terms_json', name='sc-term-json'),
    url(r'^term/add/$', 'contacts.views.term_add', name='sc-term-add-ajax'),
    url(r'^term/edit/(?P<ptid>\d+)/$', 'contacts.views.term_edit', name='sc-term-edit'),
    url(r'^term/delete/$', 'contacts.views.term_delete', name='sc-term-delete-ajax'),

    url(r'^email/add/$', 'contacts.views.contact_email_add', name='sc-email-add-ajax'),
    url(r'^email/edit/(?P<eid>\d+)/$', 'contacts.views.contact_email_edit', name='sc-email-edit'),
    url(r'^email/delete/$', 'contacts.views.sc_email_delete', name='sc-email-delete'),

    url(r'^email-type/$', 'contacts.views.view_email_types', name='sc-email-type-add-ajax'),
    url(r'^email-type/add/$', 'contacts.views.contact_email_type_add', name='sc-email-type-add-ajax'),
    url(r'^email-type/edit/(?P<etid>\d+)/$', 'contacts.views.email_type_edit', name='sc-email-type-edit'),
    url(r'^email-type/delete/$', 'contacts.views.email_type_delete', name='sc-email-type-delete'),

    url(r'^contact-type/$', 'contacts.views.view_contact_types', name='sc-contact-type-add-ajax'),
    url(r'^contact-type/add/$', 'contacts.views.contact_type_add', name='sc-contact-type-add-ajax'),
    url(r'^contact-type/edit/(?P<ctid>\d+)/$', 'contacts.views.contact_type_edit', name='sc-contact-type-edit'),
    url(r'^contact-type/delete/$', 'contacts.views.contact_type_delete', name='sc-contact-type-delete'),

    url(r'^contact-contact-type/add/$', 'contacts.views.contact_contact_type_add', name='contact-contact-type-add-ajax'),
    url(r'^contact-contact-type/edit/(?P<cctid>\d+)/$', 'contacts.views.contact_contact_type_edit', name='contact-contact-type-edit'),
    url(r'^contact-contact-type/delete/$', 'contacts.views.contact_contact_type_delete', name='contact-contact-type-delete'),


    url(r'^delivery-choice/$', 'contacts.views.view_delivery_choices', name='delivery-choice'),
    url(r'^delivery-choice/add/$', 'contacts.views.add_delivery_choices', name='add-delivery-choice'),
    url(r'^delivery-choice/edit/(?P<dcid>\d+)/$', 'contacts.views.edit_delivery_choices', name='edit-delivery-choice'),
    url(r'^delivery-choice/delete/$', 'contacts.views.delivery_choices_delete', name='delete-delivery-choice'),
    url(r'^delivery-choice/list/$', 'contacts.views.list_delivery_choices', name='delivery-choice-list'),

    url(r'^distribution-method/$', 'contacts.views.view_distribution_method', name='distribution-method'),
    url(r'^distribution-method/add/$', 'contacts.views.add_distribution_method', name='add-distribution-method'),
    url(r'^distribution-method/edit/(?P<dmid>\d+)/$', 'contacts.views.edit_distribution_method', name='edit-distribution-method'),
    url(r'^distribution-method/delete/$', 'contacts.views.delete_distribution_method', name='delete-distribution-method'),

    url(r'^contact-distribution-method/add/$', 'contacts.views.contact_distribution_method_add', name='contact-distribution-method-add-ajax'),
    url(r'^contact-distribution-method/edit/(?P<cdmid>\d+)/$', 'contacts.views.contact_distribution_method_edit', name='contact-distribution-method-edit'),
    url(r'^contact-distribution-method/delete/$', 'contacts.views.contact_distribution_method_delete', name='contact-distribution-method-delete'),


    url(r'^currency/$', 'contacts.views.view_currency', name='view-currency'),
    url(r'^currency/json/$', 'contacts.views.get_currencies', name='get-currencies'),
    url(r'^currency/add/$', 'contacts.views.add_currency', name='sc-currency-add'),
    url(r'^currency/edit/(?P<curid>\d+)/$', 'contacts.views.edit_currency', name='sc-currency-edit'),
    url(r'^currency/delete/$', 'contacts.views.delete_currency', name='sc-currency-delete'),

    url(r'^phone-type/$', 'contacts.views.view_phone_type', name='phone-type'),
    url(r'^phone-type/add/$', 'contacts.views.add_phone_type', name='add-phone-type'),
    url(r'^phone-type/edit/(?P<ptid>\d+)/$', 'contacts.views.edit_phone_type', name='edit-phone-type'),
    url(r'^phone-type/delete/$', 'contacts.views.delete_phone_type', name='delete-phone-type'),



    url(r'^comment/add/$', 'contacts.views.contact_comment_add', name='sc-comment-add-ajax'),
    url(r'^comment/edit/(?P<com_id>\d+)/$', 'contacts.views.contact_comment_edit', name='sc-comment-edit'),
    url(r'^comment/delete/$', 'contacts.views.contact_comment_delete', name='sc-comment-delete'),

    
    url(r'make-call/$', 'contacts.views.make_call'),

    url(r'^contact/reindex/$', 'contacts.views.contact_reindex', name='contact-reindex'),
)

planetwidehosting/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'planetwidehosting.views.home', name='home'),
    url(r'^user/login/$', 'planetwidehosting.views.user_login', name='user_login'),
    url(r'^user/logout/$', 'planetwidehosting.views.user_logout', name='user_logout'),
    url(r'^user/register/$', 'planetwidehosting.views.user_register', name='user_register'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^system-variable/$', 'planetwidehosting.views.sys_variable', name='sys-variable'),

    url(r'^contacts/', include('contacts.urls')),
    url(r'^inventory/', include('inventory.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
	    {'document_root', settings.STATIC_ROOT}
	  ),
)

contacts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from datetime import datetime
from contacts.choices import *
from django.contrib import messages
# Create your models here.

class DistributionMethod(models.Model):
	distribution_method = models.CharField(max_length=100, verbose_name='Distribution Method', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.distribution_method

	class Meta:
		verbose_name = "Delivery Choice"
		verbose_name_plural = "Delivery Choice"

		permissions = (
    		('view_distributionmethod', 'Can View Distribution Method'),
    	)

class DeliveryChoice(models.Model):
	delivery_choice = models.CharField(max_length=100, verbose_name='Shipping Method', help_text='', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.delivery_choice

	class Meta:
		verbose_name = "Delivery Choice"
		verbose_name_plural = "Delivery Choice"

		permissions = (
    		('view_deliverychoice', 'Can View Delivery Choice'),
    	)


class PaymentTerm(models.Model):
	term = models.CharField(max_length=25, verbose_name='Payment Terms', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.term

	class Meta:
		verbose_name = "Payment Term"
		verbose_name_plural = "Payment Term"

		permissions = (
    		('view_paymentterm', 'Can View Payment Term'),
    	)

		
class Currency(models.Model):
	currency = models.CharField(max_length=10, verbose_name="Currency", null=True, blank=True)
	currency_icon = models.CharField(max_length=2, null=True, blank=True)

	def __unicode__(self):
		return self.currency

	def get_currency_icon(self):
		if self.currency_icon:
			return dict(currency_choices)[int(self.currency_icon)]
		else:
			return dict(currency_choices)[0]


	class Meta:
		verbose_name = "Currency"
		verbose_name_plural = "Currency"

		permissions = (
    		('view_currency', 'Can View Currency'),
    	)

class Contact(models.Model):	
	contact_name 	  = models.CharField(max_length=64, verbose_name='Contact Name', null=True, blank=True)
	attention_to      = models.CharField(max_length=64, verbose_name='Attention To', null=True, blank=True)
	
	address_1         = models.CharField(max_length=64, verbose_name='Address Line 1', null=True, blank=True)
	address_2         = models.CharField(max_length=64, verbose_name='Address Line 2', null=True, blank=True)
	city              = models.CharField(max_length=64, verbose_name='city', null=True, blank=True)
	province          = models.CharField(max_length=64, verbose_name='Province or State', null=False, blank=True, default="Ontario")
	country           = models.CharField(max_length=40, verbose_name='Country', null=True, blank=False, default="Canada")
	postal_code       = models.CharField(max_length=15, verbose_name='Postal Code or ZIP', null=True, blank=True)
	webpage           = models.URLField(max_length=200, null=True, blank=True)
	search_string 	  = models.TextField(null=True, blank=True, verbose_name='Search String')

	class Meta:
		verbose_name = "Contact"
		verbose_name_plural = "Contacts"

		permissions = (
    		('view_contact', 'Can View Contact'),
    	)

	def __unicode__(self):
		return self.contact_name


class ContactProfile(models.Model):	
	contact           = models.OneToOneField(Contact,  null=False, on_delete=models.CASCADE)
	gst_number        = models.CharField(max_length=17, verbose_name='GST number', null=True, blank=True)
	gst_tax_exempt    = models.BooleanField(verbose_name='GST Tax Exempt?', blank=False, default=False)
	hst_number        = models.CharField(max_length=17, verbose_name='HST number', null=True, blank=True)
	hst_tax_exempt    = models.BooleanField(verbose_name='HST Tax Exempt?', blank=False, default=False)
	pst_number        = models.CharField(max_length=11, verbose_name='PST number', null=True, blank=True)
	pst_tax_exempt    = models.BooleanField(verbose_name='PST Tax Exempt?', blank=False, default=False)
	foreign_account   = models.CharField(max_length=30, verbose_name='Our Account # With Them', null=True, blank=True)
	mail_list         = models.CharField(max_length=15, verbose_name='Mailing List Type', null=True, blank=True)
	
	terms             = models.ForeignKey(PaymentTerm, null=True, blank=True)
	
	shipping_method   = models.ForeignKey(DeliveryChoice, null=True, blank=True)
	
	ship_collect      = models.BooleanField(verbose_name="Ship Collect?", blank=False, default=False)
	currency          = models.ForeignKey(Currency, null=True, blank=True)
	fob               = models.CharField(max_length=50, verbose_name='FOB', default='Oshawa, Ontario, Canada', null=True, blank=True)
	ap_contact        = models.TextField(null=True, blank=True, verbose_name='AP contact info', help_text='Enter Accounts Payable contact name, number and e-mail.')
	bv_ap_account 	  = models.CharField(max_length=50, verbose_name='BV A/P Account ', null=True, blank=True)
	bv_ar_account 	  = models.CharField(max_length=50, verbose_name='BV A/R Account ', null=True, blank=True)
	record_created    = models.DateTimeField(null=True, blank=True)
	last_activity     = models.DateTimeField(auto_now=True, blank=True)

	class Meta:
		verbose_name = "ContactProfile"
		verbose_name_plural = "ContactProfiles"

		permissions = (
    		('view_contactprofile', 'Can View Contact Profile'),
    	)

	def __unicode__(self):
		return self.contact.contact_name + "'s profile"

class PhoneType(models.Model):
	phone_type = models.CharField(max_length=15, verbose_name='Phone Type', null=True, blank=True)

	def __unicode__(self):
		return self.phone_type

	class Meta:
		verbose_name = "Phone Type"
		verbose_name_plural = "Phone Types"

class ContactPhone(models.Model):
	contact 		= models.ForeignKey(Contact, null=True, blank=True, related_name='contact_phone')
	phone_type      = models.ForeignKey(PhoneType, null=True, blank=True)
	phone           = models.CharField(max_length=15, verbose_name='Phone Number', null=True, blank=True)
	phone_ext       = models.CharField(max_length=10, verbose_name='Phone Extension', null=True, blank=True)

	def __unicode__(self):
		return self.phone

	class Meta:
		verbose_name = "Contact phone"
		verbose_name_plural = "Contact phones"

		permissions = (
    		('view_contactphone', 'Can View Contact Phone'),
    	)


class ContactType(models.Model):
	contact_type = models.CharField(max_length=15, verbose_name='Contact Type', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.contact_type

	class Meta:
		verbose_name = "Contact Type"
		verbose_name_plural = "Contact Types"

class ContactContactType(models.Model):
	contact 		= models.ForeignKey(Contact, null=False)
	contact_type      = models.ForeignKey(ContactType, null=True, blank=True)
	description 		= models.TextField(null=True, blank=True)

	def __unicode__(self):
		return self.contact + " / " + self.contact_type

	class Meta:
		verbose_name = "Contact Contact Type"
		verbose_name_plural = "Contact Contact Types"

		permissions = (
    		('view_contactcontacttype', 'Can View Contact Contact Type'),
    	)


class EmailAddressType(models.Model):
	email_type = models.CharField(max_length=15, verbose_name='Email Address Type', null=True, blank=False)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.email_type

	class Meta:
		verbose_name = "Email Address Type"
		verbose_name_plural = "Email Address Types"

		permissions = (
    		('view_emailaddresstype', 'Can View Email Address Type'),
    	)


class ContactEmailAddress(models.Model):
	contact 			= models.ForeignKey(Contact, null=True, blank=True, related_name='contact_emails')
	email_address_type 	= models.ForeignKey(EmailAddressType,  null=False)
	email_address 		= models.EmailField(max_length=100)

	def __unicode__(self):
		return self.email_address

	class Meta:
		verbose_name = "Email Address"
		verbose_name_plural = "Email Addresses"

		permissions = (
    		('view_contactemailaddress', 'Can View Contact Email Address'),
    	)


class ContactDistributionMethod(models.Model):
	distribution_method = models.ForeignKey(DistributionMethod,  null=False)
	contact 			= models.ForeignKey(Contact,  null=False)
	description 		= models.TextField(null=True, blank=True)

	def __unicode__(self):
		return self.contact.contact_name + " " + self.distribution_method.distribution_method

	class Meta:
		verbose_name = "Contact Distribution Method"
		verbose_name_plural = "Contact Distribution Methods"

		permissions = (
    		('view_contactdistributionmethod', 'Can View Contact Distribution Method'),
    	)


class Comment(models.Model):
	contact = models.ForeignKey(Contact,  null=False)
	staff = models.ForeignKey(User, null=True)
	comment = models.TextField(null=True, blank=True, verbose_name='Comments')
	comment_date = models.DateTimeField(auto_now=True)


	def __unicode__(self):
		return self.comment

	class Meta:
		verbose_name = "Comment"
		verbose_name_plural = "Comments"

		permissions = (
    		('view_comment', 'Can View Comments'),
    	)

planetwidehosting/models.py
from django.db import models

class SystemVariable(models.Model):
	next_item_number = models.IntegerField(null=True, blank=False)
	
	def __unicode__(self):
		return str(self.id)

	class Meta:
		verbose_name = "System variable"
		verbose_name_plural = "System variables"

		permissions = (
    		('view_system_variable', 'Can View System Variable'),
    	)

templates/base/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid main-body dashboard">
{% if messages %}
<section id="message">
	{% for message in messages %}
    	<li {% if message.tags %} class="bg-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</section>
{% endif %}

	<div class="row">
	    <div class="col-md-12">
	    <div class="row">
	    	{%if perms.auth.view_user %}
	    	<div class="col-md-4">
	    		{% include "widget/user-widget.html" %}	
	    	</div>
	    	{% endif %}

	    	{%if perms.contacts.view_contactprofile %}
	    	<div class="col-md-4">
	    		{% include "widget/contact-widget.html" %}	
	    	</div>
	    	{% endif %}

	    	<div class="col-md-4">
	    		{% include "widget/inventory-widget.html" %}	
	    	</div>

	    	<div class="col-md-4">
	    		{% include "widget/events-widget.html" %}	
	    	</div>

	    	<div class="col-md-4">
	    		{% include "widget/schedule-widget.html" %}	
	    	</div>

	    </div>
		</div>
	</div>
</div>

{% endblock content %}

templates/base/sys-variable-form.html
<table class="table">
<tr>
	<th><label for="id_next_item_number">Next Item Number:</label></th>
	<td>
		<input class="form-control" id="id_next_item_number" name="next_item_number" placeholder="Next Item Number" type="number" value="{{sv.next_item_number}}">
	</td>
</tr>
</table>

templates/base/top-nav.html
<div class="navbar navbar-inverse navbar-static-top shadow-bottom" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand scom" href="/">PLANATEWIDEHOSTING</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/">Home</a></li>

				{% if user.is_authenticated %}
					{% if perms.contacts.view_contact %}
						<li class="dropdown">
						<a href="/contacts/add/" class="dropdown-toggle" data-toggle="dropdown">Contact <b class="caret"></b></a>
						<ul class="dropdown-menu">
							{% if perms.contacts.add_contact %}
								<li><a href="/contacts/add/">Add Contact</a></li>
							{% endif %}						
							<li><a href="/contacts/">Contact List</a></li>

							{% if perms.contacts.view_contacttype %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/contact-type/">Contact Type</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_contacttype %}
										<li>
											<a href="/contacts/contact-type/add/">
												Add Contact Type
											</a>
										</li>
										{% endif %}
										<li>
											<a href="/contacts/contact-type/">
												Contact Type List
											</a>
										</li>
										
									</ul>
								</li>
							{% endif %}

							{% if perms.contacts.view_paymentterm %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/terms/">Payment Terms</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_paymentterm %}
										<li><a href="/contacts/term/add/">Add Terms</a></li>
										{% endif %}
										<li><a href="/contacts/terms/">Term List</a></li>
										
									</ul>
								</li>
							{% endif %}

							{% if perms.contacts.view_emailtype %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/email-type/">Email Types</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_emailtype %}
										<li><a href="/contacts/email-type/add/">Add Email Type</a></li>
										{% endif %}
										<li><a href="/contacts/email-type/">Email Type List</a></li>
										
									</ul>
								</li>
							{% endif %}

							{% if perms.contacts.view_deliverychoice %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/delivery-choice/">Shippling Method</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_deliverychoice %}
										<li><a href="/contacts/delivery-choice/add/">Add Shippling Method</a></li>
										{% endif %}
										<li><a href="/contacts/delivery-choice/">Shippling Method List</a></li>
										
									</ul>
								</li>
							{% endif %}

							{% if perms.contacts.view_distributionmethod %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/distribution-method/">Distribution Method</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_distributionmethod %}
										<li>
											<a href="/contacts/distribution-method/add/">
												Add Distribution Method
											</a>
										</li>
										{% endif %}
										<li>
											<a href="/contacts/distribution-method/">
												Distribution Method List
											</a>
										</li>
										
									</ul>
								</li>
							{% endif %}


							{% if perms.contacts.view_currency %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/currency/">Currency</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_currency %}
										<li><a href="/contacts/currency/add/">Add Currency</a></li>
										{% endif %}
										<li><a href="/contacts/currency/">Currency List</a></li>
										
									</ul>
								</li>
							{% endif %}

							{% if perms.contacts.view_phonetype %}
								<li class="divider"></li>
								<li class="dropdown-submenu">
								<a href="/contacts/phone-type/">Phone Type</a>
									<ul class="dropdown-menu">
										{% if perms.contacts.add_currency %}
										<li><a href="/contacts/phone-type/add/">Add Phone Type</a></li>
										{% endif %}
										<li><a href="/contacts/phone-type/">Phone Type List</a></li>
										
									</ul>
								</li>
							{% endif %}
							
						</ul>
						</li>
					{% endif %}

					{% if perms.inventory.view_item %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Inventory <b class="caret"></b></a>
							<ul class="dropdown-menu">
								{% if perms.inventory.add_item %}
								<li>
									<a href="/inventory/item/add/">
										Add Inventory Item
									</a>
								</li>
								{% endif %}
								<li>
									<a href="/inventory/list/">
										Inventory Item List
									</a>
								</li>
								
								{% if perms.inventory.view_itemunitmeasure %}
								<li class="divider"></li>

								<li class="dropdown-submenu">
									<a href="/inventory/unit-measure-list/">Item Unit Mesure</a>
									<ul class="dropdown-menu">
										{% if perms.inventory.add_itemunitmeasure %}
										<li><a href="/inventory/unit-measure/add/">Add Unit Measure</a></li>
										{% endif %}
										<li><a href="/inventory/unit-measure-list/">Unit Measure List</a></li>
										
									</ul>
								</li>
								{% endif %}

								{% if perms.inventory.view_productiontype %}
								<li class="divider"></li>

								<li class="dropdown-submenu">
									<a href="/inventory/production-type-list/">Production Type</a>
									<ul class="dropdown-menu">
										{% if perms.inventory.add_productiontype %}
										<li><a href="/inventory/production-type/add/">Add Production Type</a></li>
										{% endif %}
										<li><a href="/inventory/production-type-list/">Production Type List</a></li>
										
									</ul>
								</li>
								{% endif %}

								{% if perms.inventory.view_customsdesignation %}
								<li class="divider"></li>

								<li class="dropdown-submenu">
									<a href="/inventory/custom-designation-list/">Custom Designation</a>
									<ul class="dropdown-menu">
										{% if perms.inventory.add_customsdesignation %}
										<li><a href="/inventory/custom-designation/add/">Add Custom Designation</a></li>
										{% endif %}
										<li><a href="/inventory/custom-designation-list/">Custom Designation List</a></li>
										
									</ul>
								</li>
								{% endif %}
								{% if perms.inventory.view_location %}
								<li class="divider"></li>

								<li class="dropdown-submenu">
									<a href="/inventory/location-list/">Location</a>
									<ul class="dropdown-menu">
										{% if perms.inventory.add_location %}
										<li><a href="/inventory/location/add/">Add Location</a></li>
										{% endif %}
										<li><a href="/inventory/location-list/">Location List</a></li>
										
									</ul>
								</li>
								{% endif %}

								
							</ul>
						</li>
					{% endif %}

				{% endif %}

			</ul>


			<ul class="nav navbar-nav navbar-right">
              	<li class="">
              		<a href="/user/login/">Login </a>
            	</li>
            	<li class="">
              		<a href="/user/register/">Register </a>
            	</li>
              	<li>
              		<a href="/user/logout/">Logout</a>
              	</li>
              	
            </ul>

		</div><!--/.nav-collapse -->
	</div>
</div>

templates/base/widget.html
<section class="col-md-4 ">
	<a href="">
	<article class="widget">
		<h4>{{ perms.user.view_user }}</h4>
		{{ widget.get_total_object }}
	</article>
	</a>

</section>