contacts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'contacts.views.sc_contact_home', name='sc-contact'),
    url(r'^remove-qout/$', 'contacts.views.remove_qout', name='remove_qout'),
    url(r'^test/$', 'contacts.views.contact_test', name='contact-test'),
    url(r'^auto/$', 'contacts.views.autocomplete', name='sc-sugessions'),
    url(r'^search/$', 'contacts.views.search_contact', name='search-contact'),
    url(r'^list/$', 'contacts.views.contact_list', name='sc-contact-list'),
    url(r'^(?P<cid>\d+)/$', 'contacts.views.sc_contact_view', name='sc-contact-view'),

    url(r'^add/rel/$', 'contacts.views.sc_contact_add_rel', name='sc-contact-add'),
    url(r'^add/rel_item/$', 'contacts.views.sc_contact_add_rel_item', name='sc-contact-add-item'),
    url(r'^add/$', 'contacts.views.sc_contact_add', name='sc-contact-add'),
    url(r'^edit/(?P<pk>\d+)/$', 'contacts.views.contact_edit', name='sc-contact-edit'),
    url(r'^edit/basic/(?P<pk>\d+)/$', 'contacts.views.contact_edit_basic', name='sc-contact-edit-basic'),
    url(r'^get-contact/(?P<pk>\d+)/$', 'contacts.views.get_contact', name='get-contact'),

    url(r'^get-contact/hover/(?P<pk>\d+)/$', 'contacts.views.get_contact_hover', name='get-contact-hover'),

    url(r'^update/$', 'contacts.views.contact_update', name='sc-contact-update'),
    url(r'^profile/update/$', 'contacts.views.profile_update', name='sc-profile-update'),
    
    url(r'^delete/$', 'contacts.views.contact_delete', name='sc-contact-delete'),


    url(r'^profile/$', 'contacts.views.sc_profile', name='sc-profile'),
    
    # url(r'^update/$', 'contacts.views.sc_update', name='sc-update'),
    
    url(r'^phone/$', 'contacts.views.sc_phone_list', name='sc-phone-list'),
    url(r'^phone/add/$', 'contacts.views.contact_phone_add', name='sc-phone-add-ajax'),
    url(r'^phone/edit/(?P<pid>\d+)/$', 'contacts.views.contact_phone_edit', name='sc-phone-edit'),
    url(r'^phone/delete/$', 'contacts.views.sc_phone_delete', name='sc-phone-delete'),

    url(r'^terms/$', 'contacts.views.view_terms', name='sc-term'),
    url(r'^terms/json/$', 'contacts.views.view_terms_json', name='sc-term-json'),
    url(r'^term/add/$', 'contacts.views.term_add', name='sc-term-add-ajax'),
    url(r'^term/edit/(?P<ptid>\d+)/$', 'contacts.views.term_edit', name='sc-term-edit'),
    url(r'^term/delete/$', 'contacts.views.term_delete', name='sc-term-delete-ajax'),

    url(r'^email/add/$', 'contacts.views.contact_email_add', name='sc-email-add-ajax'),
    url(r'^email/edit/(?P<eid>\d+)/$', 'contacts.views.contact_email_edit', name='sc-email-edit'),
    url(r'^email/delete/$', 'contacts.views.sc_email_delete', name='sc-email-delete'),

    url(r'^email-type/$', 'contacts.views.view_email_types', name='sc-email-type-add-ajax'),
    url(r'^email-type/add/$', 'contacts.views.contact_email_type_add', name='sc-email-type-add-ajax'),
    url(r'^email-type/edit/(?P<etid>\d+)/$', 'contacts.views.email_type_edit', name='sc-email-type-edit'),
    url(r'^email-type/delete/$', 'contacts.views.email_type_delete', name='sc-email-type-delete'),

    url(r'^contact-type/$', 'contacts.views.view_contact_types', name='sc-contact-type-add-ajax'),
    url(r'^contact-type/add/$', 'contacts.views.contact_type_add', name='sc-contact-type-add-ajax'),
    url(r'^contact-type/edit/(?P<ctid>\d+)/$', 'contacts.views.contact_type_edit', name='sc-contact-type-edit'),
    url(r'^contact-type/delete/$', 'contacts.views.contact_type_delete', name='sc-contact-type-delete'),

    url(r'^contact-contact-type/add/$', 'contacts.views.contact_contact_type_add', name='contact-contact-type-add-ajax'),
    url(r'^contact-contact-type/edit/(?P<cctid>\d+)/$', 'contacts.views.contact_contact_type_edit', name='contact-contact-type-edit'),
    url(r'^contact-contact-type/delete/$', 'contacts.views.contact_contact_type_delete', name='contact-contact-type-delete'),


    url(r'^delivery-choice/$', 'contacts.views.view_delivery_choices', name='delivery-choice'),
    url(r'^delivery-choice/add/$', 'contacts.views.add_delivery_choices', name='add-delivery-choice'),
    url(r'^delivery-choice/edit/(?P<dcid>\d+)/$', 'contacts.views.edit_delivery_choices', name='edit-delivery-choice'),
    url(r'^delivery-choice/delete/$', 'contacts.views.delivery_choices_delete', name='delete-delivery-choice'),
    url(r'^delivery-choice/list/$', 'contacts.views.list_delivery_choices', name='delivery-choice-list'),

    url(r'^distribution-method/$', 'contacts.views.view_distribution_method', name='distribution-method'),
    url(r'^distribution-method/add/$', 'contacts.views.add_distribution_method', name='add-distribution-method'),
    url(r'^distribution-method/edit/(?P<dmid>\d+)/$', 'contacts.views.edit_distribution_method', name='edit-distribution-method'),
    url(r'^distribution-method/delete/$', 'contacts.views.delete_distribution_method', name='delete-distribution-method'),

    url(r'^contact-distribution-method/add/$', 'contacts.views.contact_distribution_method_add', name='contact-distribution-method-add-ajax'),
    url(r'^contact-distribution-method/edit/(?P<cdmid>\d+)/$', 'contacts.views.contact_distribution_method_edit', name='contact-distribution-method-edit'),
    url(r'^contact-distribution-method/delete/$', 'contacts.views.contact_distribution_method_delete', name='contact-distribution-method-delete'),


    url(r'^currency/$', 'contacts.views.view_currency', name='view-currency'),
    url(r'^currency/json/$', 'contacts.views.get_currencies', name='get-currencies'),
    url(r'^currency/add/$', 'contacts.views.add_currency', name='sc-currency-add'),
    url(r'^currency/edit/(?P<curid>\d+)/$', 'contacts.views.edit_currency', name='sc-currency-edit'),
    url(r'^currency/delete/$', 'contacts.views.delete_currency', name='sc-currency-delete'),

    url(r'^phone-type/$', 'contacts.views.view_phone_type', name='phone-type'),
    url(r'^phone-type/add/$', 'contacts.views.add_phone_type', name='add-phone-type'),
    url(r'^phone-type/edit/(?P<ptid>\d+)/$', 'contacts.views.edit_phone_type', name='edit-phone-type'),
    url(r'^phone-type/delete/$', 'contacts.views.delete_phone_type', name='delete-phone-type'),



    url(r'^comment/add/$', 'contacts.views.contact_comment_add', name='sc-comment-add-ajax'),
    url(r'^comment/edit/(?P<com_id>\d+)/$', 'contacts.views.contact_comment_edit', name='sc-comment-edit'),
    url(r'^comment/delete/$', 'contacts.views.contact_comment_delete', name='sc-comment-delete'),

    
    url(r'make-call/$', 'contacts.views.make_call'),

    url(r'^contact/reindex/$', 'contacts.views.contact_reindex', name='contact-reindex'),
)

planetwidehosting/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'planetwidehosting.views.home', name='home'),
    url(r'^user/login/$', 'planetwidehosting.views.user_login', name='user_login'),
    url(r'^user/logout/$', 'planetwidehosting.views.user_logout', name='user_logout'),
    url(r'^user/register/$', 'planetwidehosting.views.user_register', name='user_register'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^system-variable/$', 'planetwidehosting.views.sys_variable', name='sys-variable'),

    url(r'^contacts/', include('contacts.urls')),
    url(r'^inventory/', include('inventory.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
	    {'document_root', settings.STATIC_ROOT}
	  ),
)

contacts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from datetime import datetime
from contacts.choices import *
from django.contrib import messages
# Create your models here.

class DistributionMethod(models.Model):
	distribution_method = models.CharField(max_length=100, verbose_name='Distribution Method', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.distribution_method

	class Meta:
		verbose_name = "Delivery Choice"
		verbose_name_plural = "Delivery Choice"

		permissions = (
    		('view_distributionmethod', 'Can View Distribution Method'),
    	)

class DeliveryChoice(models.Model):
	delivery_choice = models.CharField(max_length=100, verbose_name='Shipping Method', help_text='', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.delivery_choice

	class Meta:
		verbose_name = "Delivery Choice"
		verbose_name_plural = "Delivery Choice"

		permissions = (
    		('view_deliverychoice', 'Can View Delivery Choice'),
    	)


class PaymentTerm(models.Model):
	term = models.CharField(max_length=25, verbose_name='Payment Terms', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.term

	class Meta:
		verbose_name = "Payment Term"
		verbose_name_plural = "Payment Term"

		permissions = (
    		('view_paymentterm', 'Can View Payment Term'),
    	)

		
class Currency(models.Model):
	currency = models.CharField(max_length=10, verbose_name="Currency", null=True, blank=True)
	currency_icon = models.CharField(max_length=2, null=True, blank=True)

	def __unicode__(self):
		return self.currency

	def get_currency_icon(self):
		if self.currency_icon:
			return dict(currency_choices)[int(self.currency_icon)]
		else:
			return dict(currency_choices)[0]


	class Meta:
		verbose_name = "Currency"
		verbose_name_plural = "Currency"

		permissions = (
    		('view_currency', 'Can View Currency'),
    	)

class Contact(models.Model):	
	contact_name 	  = models.CharField(max_length=64, verbose_name='Contact Name', null=True, blank=True)
	attention_to      = models.CharField(max_length=64, verbose_name='Attention To', null=True, blank=True)
	
	address_1         = models.CharField(max_length=64, verbose_name='Address Line 1', null=True, blank=True)
	address_2         = models.CharField(max_length=64, verbose_name='Address Line 2', null=True, blank=True)
	city              = models.CharField(max_length=64, verbose_name='city', null=True, blank=True)
	province          = models.CharField(max_length=64, verbose_name='Province or State', null=False, blank=True, default="Ontario")
	country           = models.CharField(max_length=40, verbose_name='Country', null=True, blank=False, default="Canada")
	postal_code       = models.CharField(max_length=15, verbose_name='Postal Code or ZIP', null=True, blank=True)
	webpage           = models.URLField(max_length=200, null=True, blank=True)
	search_string 	  = models.TextField(null=True, blank=True, verbose_name='Search String')

	class Meta:
		verbose_name = "Contact"
		verbose_name_plural = "Contacts"

		permissions = (
    		('view_contact', 'Can View Contact'),
    	)

	def __unicode__(self):
		return self.contact_name


class ContactProfile(models.Model):	
	contact           = models.OneToOneField(Contact,  null=False, on_delete=models.CASCADE)
	gst_number        = models.CharField(max_length=17, verbose_name='GST number', null=True, blank=True)
	gst_tax_exempt    = models.BooleanField(verbose_name='GST Tax Exempt?', blank=False, default=False)
	hst_number        = models.CharField(max_length=17, verbose_name='HST number', null=True, blank=True)
	hst_tax_exempt    = models.BooleanField(verbose_name='HST Tax Exempt?', blank=False, default=False)
	pst_number        = models.CharField(max_length=11, verbose_name='PST number', null=True, blank=True)
	pst_tax_exempt    = models.BooleanField(verbose_name='PST Tax Exempt?', blank=False, default=False)
	foreign_account   = models.CharField(max_length=30, verbose_name='Our Account # With Them', null=True, blank=True)
	mail_list         = models.CharField(max_length=15, verbose_name='Mailing List Type', null=True, blank=True)
	
	terms             = models.ForeignKey(PaymentTerm, null=True, blank=True)
	
	shipping_method   = models.ForeignKey(DeliveryChoice, null=True, blank=True)
	
	ship_collect      = models.BooleanField(verbose_name="Ship Collect?", blank=False, default=False)
	currency          = models.ForeignKey(Currency, null=True, blank=True)
	fob               = models.CharField(max_length=50, verbose_name='FOB', default='Oshawa, Ontario, Canada', null=True, blank=True)
	ap_contact        = models.TextField(null=True, blank=True, verbose_name='AP contact info', help_text='Enter Accounts Payable contact name, number and e-mail.')
	bv_ap_account 	  = models.CharField(max_length=50, verbose_name='BV A/P Account ', null=True, blank=True)
	bv_ar_account 	  = models.CharField(max_length=50, verbose_name='BV A/R Account ', null=True, blank=True)
	record_created    = models.DateTimeField(null=True, blank=True)
	last_activity     = models.DateTimeField(auto_now=True, blank=True)

	class Meta:
		verbose_name = "ContactProfile"
		verbose_name_plural = "ContactProfiles"

		permissions = (
    		('view_contactprofile', 'Can View Contact Profile'),
    	)

	def __unicode__(self):
		return self.contact.contact_name + "'s profile"

class PhoneType(models.Model):
	phone_type = models.CharField(max_length=15, verbose_name='Phone Type', null=True, blank=True)

	def __unicode__(self):
		return self.phone_type

	class Meta:
		verbose_name = "Phone Type"
		verbose_name_plural = "Phone Types"

class ContactPhone(models.Model):
	contact 		= models.ForeignKey(Contact, null=True, blank=True, related_name='contact_phone')
	phone_type      = models.ForeignKey(PhoneType, null=True, blank=True)
	phone           = models.CharField(max_length=15, verbose_name='Phone Number', null=True, blank=True)
	phone_ext       = models.CharField(max_length=10, verbose_name='Phone Extension', null=True, blank=True)

	def __unicode__(self):
		return self.phone

	class Meta:
		verbose_name = "Contact phone"
		verbose_name_plural = "Contact phones"

		permissions = (
    		('view_contactphone', 'Can View Contact Phone'),
    	)


class ContactType(models.Model):
	contact_type = models.CharField(max_length=15, verbose_name='Contact Type', null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.contact_type

	class Meta:
		verbose_name = "Contact Type"
		verbose_name_plural = "Contact Types"

class ContactContactType(models.Model):
	contact 		= models.ForeignKey(Contact, null=False)
	contact_type      = models.ForeignKey(ContactType, null=True, blank=True)
	description 		= models.TextField(null=True, blank=True)

	def __unicode__(self):
		return self.contact + " / " + self.contact_type

	class Meta:
		verbose_name = "Contact Contact Type"
		verbose_name_plural = "Contact Contact Types"

		permissions = (
    		('view_contactcontacttype', 'Can View Contact Contact Type'),
    	)


class EmailAddressType(models.Model):
	email_type = models.CharField(max_length=15, verbose_name='Email Address Type', null=True, blank=False)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.email_type

	class Meta:
		verbose_name = "Email Address Type"
		verbose_name_plural = "Email Address Types"

		permissions = (
    		('view_emailaddresstype', 'Can View Email Address Type'),
    	)


class ContactEmailAddress(models.Model):
	contact 			= models.ForeignKey(Contact, null=True, blank=True, related_name='contact_emails')
	email_address_type 	= models.ForeignKey(EmailAddressType,  null=False)
	email_address 		= models.EmailField(max_length=100)

	def __unicode__(self):
		return self.email_address

	class Meta:
		verbose_name = "Email Address"
		verbose_name_plural = "Email Addresses"

		permissions = (
    		('view_contactemailaddress', 'Can View Contact Email Address'),
    	)


class ContactDistributionMethod(models.Model):
	distribution_method = models.ForeignKey(DistributionMethod,  null=False)
	contact 			= models.ForeignKey(Contact,  null=False)
	description 		= models.TextField(null=True, blank=True)

	def __unicode__(self):
		return self.contact.contact_name + " " + self.distribution_method.distribution_method

	class Meta:
		verbose_name = "Contact Distribution Method"
		verbose_name_plural = "Contact Distribution Methods"

		permissions = (
    		('view_contactdistributionmethod', 'Can View Contact Distribution Method'),
    	)


class Comment(models.Model):
	contact = models.ForeignKey(Contact,  null=False)
	staff = models.ForeignKey(User, null=True)
	comment = models.TextField(null=True, blank=True, verbose_name='Comments')
	comment_date = models.DateTimeField(auto_now=True)


	def __unicode__(self):
		return self.comment

	class Meta:
		verbose_name = "Comment"
		verbose_name_plural = "Comments"

		permissions = (
    		('view_comment', 'Can View Comments'),
    	)

templates/contacts/partials/add-email-address-type-partial.html
<span class="label label-danger {{ email_type.id }}">
	{{ email_type.email_type }}
	{% if perms.contacts.change_emailaddresstype %}
		<a class="email-type-edit" href="/contacts/email-type/edit/{{ email_type.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-id="{{ email_type.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/contacts/partials/add-paymentterm-partial.html
<span class="label label-danger {{ payment_term.id }}">
	{{ payment_term.term }}
	{% if perms.contacts.change_paymentterm %}
		<a class="payment-term-edit" href="/contacts/term/edit/{{ payment_term.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-id="{{ payment_term.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/contacts/partials/add-phone-type-partial.html
<span class="label label-danger {{ phone_type.id }}">
	{{ phone_type.phone_type }}
	{% if perms.contacts.change_currency %}
		<a class="phone-type-edit" href="/contacts/phone-type/edit/{{ phone_type.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-id="{{ phone_type.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/contacts/partials/comment-add-form-partial.html
<div id="comment-form" style="padding-top: 20px; padding-bottom: 20px;">
	<form id="contactComment">
		<table width="100%">
			<tr>
				<td>
					<input type="hidden" name="cid" value="{{ cid }}">
				</td>
			</tr>
			<tr>
				<td>
					<textarea class="form-control" name="comment" placeholder="Comments here" rows="5"></textarea>
				</td>
			</tr>
			<tr>
				<td>
					<input type="submit" class="btn btn-danger btn-lg comment" value="Submit Comment">
				</td>
			</tr>
	
	    </table>
	</form>
</div>
<script type="text/javascript">
(function(){
	$("form#contactComment").on("submit", function(e){
		e.preventDefault();
		form_data = $(this).serialize();
		console.log(form_data);

		$.ajax({
			type: "POST",
			url: "/contacts/comment/add/",
			data: form_data,
			success: function(rdata) {
				$("#comment").append(rdata);

			},
			errors: function() {

			}
		})

	});
})();
</script>

templates/contacts/partials/comment-partial.html
<section class="panel panel-info comment">
	<div class="panel-body">
		{{ comment.comment }}
		<p>
		{% if perms.contacts.change_comment %}
			<span><a class="comment-edit" href="/contacts/comment/edit/{{ comment.id }}/" 
							data-toggle="modal" data-target="#editModal"
							data-id="{{ comment.id }}"><i class="glyphicon glyphicon-edit"></i></a></span>
		{% endif %}

		{% if perms.contacts.delete_comment %}
			 / <span><a class="comment-delete" href="/contacts/comment/delete/" data-id="{{ comment.id }}">
			 <i class="glyphicon glyphicon-remove"></i></a></span>
		{% endif %}
		</p>

	</div>

	<script type="text/javascript">
	(function(){
		$("div.message").hide();

		$("a.comment-edit").on("click", function(e){
			e.preventDefault();
			
		    url = $(this).attr("href");
			mdal = $('#editModal');
			mdal.on("shown.bs.modal", function(){
				$("#editModal .modal-content").load(url);
				console.log(url);
			}).modal();

			return false;
		});

		$("a.comment-delete").on("click", function(e){
			e.preventDefault();
			com_id = $(this).data("id")

			$( "#delete-comment-confirm" ).dialog({
				resizable: false,
				height:200,
				modal: true,
				buttons: {
					"Delete Comment": function() {
										
						$( this ).dialog( "close" );
						$.ajax({
							type: "POST",
							url: "/contacts/comment/delete/",
							data: {
								'com_id': com_id
							},
							success: function(rdata) {
								console.log(rdata);
								$("a[data-id='"+rdata+"']").closest("section").remove();
							}
						})
					},
					Cancel: function() {
						$( this ).dialog( "close" );
					}
				}
			});
		});

	})(jQuery)

	</script>



<div id="delete-comment-confirm" title="Do you want to delete?">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">
  </span>This will delete the comment from your system?</p>
</div>
</section>

templates/contacts/partials/contact-contact-type-partial.html
<div class="col-md-12">
	<section class="panel panel-primary">
		<div class="panel-heading"><h4>Contact Type</h4></div>
		<div class="panel-body">
		{% if perms.contacts.add_contactcontacttype %}
			<form name='contact-contact-type' method="POST">{% csrf_token %}
				<input type="hidden" name="cid" value="{{ cid }}">
				<table>
					<tr>
						{% for field in cctform %}
							<td>
							{{ field.label_tag }}
							</td>
						{% endfor %}
							<td></td>
					</tr>
					<tr>
						
						{% for field in cctform %}
						<td>
							
							
							{{ field }}
						</td>		
						{% endfor %}
						<td>
							<div class="input-group-btn">
								<button class="btn btn-primary btn-lg" type="submit">Add</button>
							</div>
						</td>
					</tr>
					
				</table>


			</form>
		{% endif %}

			
			<table class="table table-hover table-bordered email-list">
				<thead>
					<tr class="danger">
						<th> ID </th>
						<th>Contact Type</th>
						<th>Description</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody id='contact-contact-type-list'>
					{% for contact_contact_type in contact_contact_types %}
					<tr class="{{ contact_contact_type.id }}">
						<td>{{ contact_contact_type.id }}</td>
						<td>{{ contact_contact_type.contact_type }}</td>
						<td>{{ contact_contact_type.description }}</td>
						
						<td>
							<a class="contact-contact-type-edit" href="/contacts/contact-contact-type/edit/{{ contact_contact_type.id }}/" 
							data-toggle="modal" data-target="#editModal"
							data-id="{{ contact_contact_type.id }}">edit</a> / 
						
							<a class="contact-contact-type-delete" href="#" data-id="{{ contact_contact_type.id }}">delete</a>
						
						</td>
					</tr>
					{% empty %}
						<tr class="warning">
							<td colspan="4"> No contact type availabe
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
			
		</div>
	</section>				

{% include "modals/edit-modal.html" %}


<script type="text/javascript">
	(function(){

		$("a.contact-contact-type-edit").on("click", function(e){
		
			e.preventDefault();
			pid = $(this).data("id");
		    url = $(this).attr("href");
			mdal = $('#editModal');
			mdal.on("shown.bs.modal", function(){
				$("#editModal .modal-content").load(url);
				console.log(url);
			}).modal();

			return false;
		})

		$("form[name='contact-contact-type']").on("submit", function(e){
			e.preventDefault();

			form_data = $(this).serialize()
			
			// console.log(phone_type + " "+ phone + " "+ phone_ext);
			$.ajax({
				type: "post",
				url: "/contacts/contact-contact-type/add/",
				data: form_data,
				success: function(data){
					$("tbody#contact-contact-type-list tr.warning").remove()
					$("tbody#contact-contact-type-list").append(data)
					console.log(data);
				}
			});
		});

		$("a.contact-contact-type-delete").on("click", function(e){
			e.preventDefault();
			cctid = $(this).data("id");

			$( "#delete-contact-contact-type-confirm" ).dialog({
				resizable: false,
				height:200,
				modal: true,
				buttons: {
					"Delete Email": function() {
										
						$( this ).dialog( "close" );
						$.ajax({
							type: 'post',
							url: "/contacts/contact-contact-type/delete/",
							data: {
								'cctid': cctid,
							},

							success: function(data){
								console.log(data);
								$("a[data-id='"+data+"'").closest("tr").remove();
							},
							errors: function(data){
								alert("Phone is not deleted.");
							}
						})
					},
					Cancel: function() {
						$( this ).dialog( "close" );
					}
				}
			});

		});

	})(jQuery)
</script>


<div id="delete-contact-contact-type-confirm" title="Do you want to delete?">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;">
  </span>This will delete the contact type from contact ?</p>
</div>
</div>

templates/contacts/partials/contact-distribution-method-item-tmpl.html
<tr class="{{ contact_distribution_method.id }}">
	<td>{{ contact_distribution_method.id }}</td>
	<td>{{ contact_distribution_method.distribution_method }}</td>
	<td>{{ contact_distribution_method.description }}</td>
	
	<td>
		
		<a class="contact-distribution-method-edit" href="/contacts/contact-distribution-method/edit/{{ contact_distribution_method.id }}/" 
		data-id="{{ contact_distribution_method.id }}" data-toggle="modal" data-target="#editModal" >edit</a> / 
		<a class='contact-distribution-method-delete' href='#' data-id="{{ contact_distribution_method.id }}">delete</a>
	</td>
</tr>